#######################################
# AWS Region
#######################################

variable "aws_region" {
  description = "AWS Region"
  type        = string
  default     = "us-east-1"
}

#######################################
# Dev, test, and production EC2 sizing
#######################################

variable "environment_instances" {
  description = "Exactly three EC2 environments and the capacity assigned to each full service stack"

  type = map(object({
    instance_type    = string
    root_volume_size = number
    subnet_cidr      = string
  }))

  default = {
    dev = {
      instance_type    = "m7i.2xlarge"
      root_volume_size = 150
      subnet_cidr      = "10.42.10.0/24"
    }
    test = {
      instance_type    = "m7i.2xlarge"
      root_volume_size = 150
      subnet_cidr      = "10.42.20.0/24"
    }
    production = {
      instance_type    = "m7i.4xlarge"
      root_volume_size = 300
      subnet_cidr      = "10.42.30.0/24"
    }
  }

  validation {
    condition     = toset(keys(var.environment_instances)) == toset(["dev", "test", "production"])
    error_message = "environment_instances must contain exactly dev, test, and production."
  }

  validation {
    condition = alltrue([
      for environment in values(var.environment_instances) :
      environment.root_volume_size >= 100
    ])
    error_message = "Each environment needs at least 100 GB for the combined container images and persistent volumes."
  }

  validation {
    condition = alltrue([
      for environment in values(var.environment_instances) :
      can(cidrnetmask(environment.subnet_cidr))
    ])
    error_message = "Each environment subnet_cidr must be a valid IPv4 CIDR."
  }
}

#######################################
# DevCloud Request ID
#######################################

variable "request_id" {
  description = "Unique request ID generated by the DevCloud Portal"
  type        = string
}

#######################################
# Key Pair Prefix
#######################################

variable "key_name_prefix" {
  description = "Prefix for the generated SSH Key Pair"
  type        = string
  default     = "terraform-key"
}

#######################################
# Security Group Prefix
#######################################

variable "security_group_prefix" {
  description = "Prefix for the Security Group"
  type        = string
  default     = "runtime-security-group"
}

########################################################
# MySQL
########################################################

variable "mysql_root_password" {
  description = "MySQL Root Password"
  type        = string
  sensitive   = true
}

variable "mysql_database" {
  description = "MySQL Database Name"
  type        = string
}

variable "mysql_user" {
  description = "MySQL Username"
  type        = string
}

variable "mysql_password" {
  description = "MySQL User Password"
  type        = string
  sensitive   = true
}

########################################################
# MariaDB
########################################################

variable "mariadb_root_password" {
  description = "MariaDB Root Password"
  type        = string
  sensitive   = true
}

variable "mariadb_database" {
  description = "MariaDB Database Name"
  type        = string
}

variable "mariadb_user" {
  description = "MariaDB Username"
  type        = string
}

variable "mariadb_password" {
  description = "MariaDB User Password"
  type        = string
  sensitive   = true
}

########################################################
# PostgreSQL
########################################################

variable "postgres_user" {
  description = "PostgreSQL Username"
  type        = string
}

variable "postgres_password" {
  description = "PostgreSQL Password"
  type        = string
  sensitive   = true
}

variable "postgres_database" {
  description = "PostgreSQL Database"
  type        = string
}

########################################################
# MongoDB
########################################################

variable "mongodb_user" {
  description = "MongoDB Root Username"
  type        = string
}

variable "mongodb_password" {
  description = "MongoDB Root Password"
  type        = string
  sensitive   = true
}

########################################################
# Jupyter Notebook
########################################################

variable "jupyter_token" {
  description = "Jupyter Notebook Access Token"
  type        = string
  sensitive   = true
}

########################################################
# Missing-service platform
########################################################

variable "platform_allowed_cidrs" {
  description = "CIDR ranges allowed to reach the public platform service ports; narrow this for non-demo deployments"
  type        = list(string)
  default     = ["0.0.0.0/0"]

  validation {
    condition     = length(var.platform_allowed_cidrs) > 0 && alltrue([for cidr in var.platform_allowed_cidrs : can(cidrnetmask(cidr))])
    error_message = "platform_allowed_cidrs must contain at least one valid IPv4 CIDR."
  }
}

variable "platform_nifi_username" {
  description = "Single-user administrator name for the private NiFi UI"
  type        = string
  default     = "admin"

  validation {
    condition     = length(var.platform_nifi_username) >= 4
    error_message = "platform_nifi_username must contain at least four characters."
  }
}

variable "platform_images" {
  description = "Pinned public images used by the missing-service platform"
  type = object({
    static_web = string
    tensorflow = string
    kong       = string
    nifi       = string
    mediamtx   = string
  })

  default = {
    static_web = "nginx:1.28.0-alpine"
    tensorflow = "tensorflow/serving:2.20.0"
    kong       = "kong/kong-gateway:3.10.0.2"
    nifi       = "apache/nifi:2.10.0"
    mediamtx   = "bluenviron/mediamtx:1.18.2"
  }
}

variable "faas_public_access" {
  description = "Whether the demonstration Lambda Function URL is public; set false to require AWS IAM signed requests"
  type        = bool
  default     = true
}
